

[config]

save_backend="mysql"

database="test_iter"
save_dir="test_loc_iter"

exp_file="examples/experiment.jl"
exp_module_name = "Main"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps=102902

[sweep_args]
opt2 = [5,6,7,8,9]
opt1 = "1:50"
"opt3+opt4" = [["a", 1], ["b", 2], ["c", 3]]