

[config]

save_backend="mysql" # mysql only database backend supported
connection_file="examples/connection_file.toml" # will default to ~/.mysql_connection_info.toml
database="test_iter" # for params and resutsl
save_dir="test_loc_iter" # for exceptions, settings, and more!

exp_file="examples/experiment.jl"
exp_module_name = "Main"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps=102902

[sweep_args]
opt2 = [5,6,7,8,9]
opt1 = "1:50"
"opt3+opt4" = [["a", 1], ["b", 2], ["c", 3]]