

[config]
save_dir="test_loc"
exp_file="experiment.jl"
exp_module_name = "TestExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps=102902

[sweep_args]
opt2 = [5,6,7,8,9]
opt1 = "1:50"
"opt3+opt4" = [["a", 1], ["b", 2], ["c", 3]]