

[config]

save_backend="mysql" # mysql only database backend supported
database="test_iter" # for params and resutsl
save_dir="test_iter_sql" # for exceptions, settings, and more!

exp_file="experiment.jl"
exp_module_name = "TestExperiment"
exp_func_name = "main_experiment"
arg_iter_type = "iter"

[static_args]
steps=102902

[sweep_args]
opt2 = [5,6,7,8,9]
opt1 = "1:50"
"opt3+opt4" = [["a", 1], ["b", 2], ["c", 3]]
